api:
  port: 8081

database:
  mongodb:
    #url: mongodb+srv://adminDB:epsilon1@cluster0.b7amm.mongodb.net/yai-commander?retryWrites=true&w=majority
    #url: mongodb://localhost/mth40?retryWrites=true&w=majority
    debug: true